[package]
name = "fatty"
version = "0.1.0"
edition = "2024"
default-run = "fatty"

[dependencies]
bitflags = "2.11.0"
futures = "0.3.32"
#brush-core = "0.4.0"
glob = "0.3.3"
iced = { git = "https://github.com/iced-rs/iced", rev = "ac1b2c7123ad82643482c0b3a4a776246c966697", features = [ "advanced", "image", "canvas", "lazy", "qr_code", "tokio" ]}
image = { version = "0.25", default-features = false, features = ["avif", "bmp", "gif", "ico", "jpeg", "png", "webp"] }
inotify = "0.11.1"
itertools = "0.14.0"
libc = "0.2.184"
pest = "2.8.6"
pest_derive = "2.8.6"
raw-window-handle = "0.6"
rustix = "1.1.4"
rustix-openpty = "0.2.0"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.51.0", features = ["sync"] }
unicode-segmentation = "1.13.2"
#smol = "2.0"
vte = { version = "0.15.0", features = ["bitflags", "ansi"] }
