WHITESPACE    = _{ " " | "\t" }

program       =  { SOI ~ stmt+ ~ EOI }
stmt          =  { background | chain | pipeline | sub | command }
background    =  { (chain | pipeline | sub | command) ~ "&" }
chain         =  { (pipeline | sub | command) ~ (connector ~ (pipeline | sub | command))+ }
pipeline      =  { (sub | command) ~ ("|" ~ (sub | command))+ }
sub           =  { "(" ~ stmt+ ~ ")" }
command       =  { token+ }

connector     =  { "&&" | "||" }

token         = _{ single_quoted | double_quoted | unquoted } // | var }
// var           =  { "$" ~ ('a'..'z' | 'A'..'Z' | '0'..'9')+ }
single_quoted = @{ "'" ~ (!"'" ~ ANY)* ~ "'" }
double_quoted = @{ "\"" ~ ("\\" ~ ANY | !"\"" ~ ANY)* ~ "\"" }
unquoted      = @{
    ( !("$" | " " | "\t" | "\n" | "'" | "\"" | "\\" | "|" | "&" | "(" | ")") ~ ANY
    | "\\" ~ ANY
    )+
}
