WHITESPACE    = _{ " " | "\t" }

program       =  { SOI ~ stmt+ ~ EOI }
stmt          =  { (assignment | background | chain | pipeline | b_expr | sub | command) ~ "\n"* }
background    =  { (chain | pipeline | sub | command) ~ "&" }
chain         =  { (pipeline | b_expr | sub | command) ~ (connector ~ (pipeline | b_expr | sub | command))+ }
pipeline      =  { (sub | special | command | special) ~ ("|" ~ (sub | special | command | special))+ }
sub           =  { "(" ~ stmt+ ~ ")" }
command       =  { unquoted ~ single* }
assignment    =  { var ~ "=" ~ (token | stmt) }

connector     =  { "&&" | "||" }

special       = _{ s_where }
s_where       =  { "where" ~ stmt+ }
//until       =  { "until" ~ stmt+ }
//break       =  { "break" }
//continue    =  { "continue" }

b_expr        = {
      prefix+ ~ atom ~ (infix ~ prefix* ~ atom)*
    | small_op ~ (infix ~ prefix* ~ atom)*
    | atom ~ (infix ~ prefix* ~ atom)+
}
atom          = _{ small_op | sub | token }
small_op      =  { single ~ ops ~ single }
single        = _{ sub | token }

infix         = _{ b_and_op | b_xor_op | b_or_op }
prefix        = _{ b_not_op }

b_and_op      =  { "-and" ~ !(ASCII_ALPHANUMERIC | "_") }
b_xor_op      =  { "-xor" ~ !(ASCII_ALPHANUMERIC | "_") }
b_or_op       =  { "-or"  ~ !(ASCII_ALPHANUMERIC | "_") }
b_not_op      =  { "-not" ~ !(ASCII_ALPHANUMERIC | "_") }
ops           = @{ ("-eq"|"-ne"|"-ge"|"-gt"|"-le"|"-lt"|"-lk"|"-nk"|"-"|"+"|"*"|"/") ~ !(ASCII_ALPHANUMERIC | "_") }

// token: a value, may contain a value or a computable expression
token         = _{ var | table | array | literal | unquoted }

var           =  { "$" ~ var_name ~ var_suffix* }
var_name      = @{ (ASCII_ALPHANUMERIC | "_")+ }
var_suffix    = _{ field_col | field_col_br | field_index_l | field_index }
field_col     = @{ "." ~ (ASCII_ALPHANUMERIC | "_")+ }
field_col_br  =  { ".[" ~ stmt ~ "]" }
field_index_l =  { "[" ~ literal ~ "]" }
field_index   =  { "[" ~ stmt ~ "]" }

table         =  { "[" ~ NEWLINE* ~ header_row ~ NEWLINE* ~ ";" ~ NEWLINE* ~ (row ~ NEWLINE*)* ~ "]" }
header_row    =  { "[" ~ single+ ~ "]" }
col_name      = @{ (ASCII_ALPHANUMERIC | "_")+ }
row           =  { "[" ~ single+ ~ "]" }
array         =  { "[" ~ single* ~ "]" }

// literal: simple literal, cannot contain expressions
// TODO: this can be merged with token by modifying the parser slightly
literal       = _{ float_lit | integer | single_quoted | double_quoted }

float_lit     = @{ integer ~ "." ~ integer }
integer       = @{ ('0'..'9')+ }
single_quoted = @{ "'" ~ (!"'" ~ ANY)* ~ "'" }
double_quoted = @{ "\"" ~ ("\\" ~ ANY | !"\"" ~ ANY)* ~ "\"" }
unquoted      = @{
    ( !("$" | " " | "\t" | "\n" | "'" | "\"" | "\\" | "|" | "&" | "(" | ")" | "[" | "]") ~ ANY
    | "\\" ~ ANY
    )+
}
